version: 2
updates:


  # Перевірка оновлень для Node.js (сервіс Checkout)
  - package-ecosystem: "npm"
    directory: "/src/checkout"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Перевірка оновлень для Java/Maven (сервіси UI, Cart, Orders)
  - package-ecosystem: "maven"
    directory: "/src/ui"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    
  - package-ecosystem: "maven"
    directory: "/src/cart"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    
  - package-ecosystem: "maven"
    directory: "/src/orders"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10

  # Оновлення для GitHub Actions (якщо ви їх використовуєте)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
