services:
  catalog:
    build:
      context: .
    hostname: catalog
    depends_on:
      - catalog-db
    restart: always
    cap_drop:
      - all
    security_opt:
      - no-new-privileges:true
    environment:
      - GIN_MODE=release
      - reschedule=on-node-failure
      - RETAIL_CATALOG_PERSISTENCE_PROVIDER=mysql
      - RETAIL_CATALOG_PERSISTENCE_PASSWORD=${MYSQL_PASSWORD}
      - RETAIL_CATALOG_PERSISTENCE_ENDPOINT=catalog-db:3306
    ports:
      - "8081:8080"
    develop:
      watch:
        - action: rebuild
          path: .

  # nosemgrep: yaml.docker-compose.security.writable-filesystem-service.writable-filesystem-service
  catalog-db:
    image: mariadb:10.9
    hostname: catalog-db
    restart: always
    security_opt:
      - no-new-privileges:true
    environment:
      - reschedule=on-node-failure
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=sampledb
      - MYSQL_USER=catalog_user
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
