AWSTemplateFormatVersion: '2010-09-09'
Description: Deploys the Retail Store Sample App

Parameters:
  ResourceBucket:
    Type: String
    Description: S3Bucket Bucket where the Resources are stored (cloudformation, images, lambda code)

  ResourceBucketRelativePath:
    Type: String
    Description: S3Bucket Path where the Resources are stored (cloudformation, images, lambda code) (i.e. path/path2), can be empty if resources are at the root of the bucket. MUST contain trailing /
  
  EnvironmentName:
    Type: String
    Description: Name of environment chosen for deployment

Resources:
 #IAM
  IAM:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${ResourceBucket}/${ResourceBucketRelativePath}/lib/ecs/iam.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
  
  #RDS
  RDS:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${ResourceBucket}/${ResourceBucketRelativePath}/lib/dependencies/catalog_rds.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        # VpcId: !GetAtt VPC.Outputs.VpcId
        PrivateSubnets: !GetAtt VPC.Outputs.PrivateSubnets
        AllowedSecurityGroupIds: !GetAtt SecurityGroups.Outputs.RDSSecurityGroup

  # Buckets
  # Buckets:
  #   Type: AWS::CloudFormation::Stack
  #   Properties:
  #     TemplateURL: !Sub https://s3.amazonaws.com/${ResourceBucket}/${ResourceBucketRelativePath}cloudformation-templates/base/buckets.yaml
  #     Parameters:
  #       CleanupBucketLambdaArn: !Ref CleanupBucketLambdaArn

  VPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${ResourceBucket}/${ResourceBucketRelativePath}/lib/vpc.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcCIDR: 10.0.0.0/16
        Subnet1CIDR: 10.0.0.0/24
        Subnet2CIDR: 10.0.1.0/24
        Subnet3CIDR: 10.0.2.0/24
        PublicSubnet1CIDR: 10.0.10.0/24
        PublicSubnet2CIDR: 10.0.11.0/24
        PublicSubnet3CIDR: 10.0.12.0/24
  
  SecurityGroups:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${ResourceBucket}/${ResourceBucketRelativePath}/lib/dependencies/security_groups.yaml
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        VpcId: !GetAtt VPC.Outputs.VpcId
