server:
  port: ${port:8080}
  compression.enabled: true

spring:
  messages:
    basename: lang/messages
  codec:
    max-in-memory-size: 10MB

retail:
  ui:
    metadata:
      region: "none"
    theme: default
    endpoints:
      catalog: false # http://localhost:8081
      carts: false # http://localhost:8081
      checkout: http://localhost:8082

management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,prometheus
