version: 2.1

# Використовуємо Docker як середовище для виконання
executors:
  docker-executor:
    docker:
      - image: cimg/go:1.21 # Офіційний образ для Go

jobs:
  # 1. Етап збірки
  build:
    executor: docker-executor
    steps:
      - checkout # Завантажуємо код з репозиторію
      - setup_remote_docker # Дозволяє запускати команди docker всередині контейнера
      
      - run:
          name: "Збірка Docker образу"
          command: |
            # Будуємо образ просто для перевірки, що Dockerfile робочий
            docker build -t retail-app-test .
            
      - run:
          name: "Компіляція Go коду"
          command: |
            go mod download
            go build -v ./...

  # 2. Етап тестування
  test:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: "Запуск Unit тестів"
          command: |
            go test -v ./...

# Описуємо черговість
workflows:
  version: 2
  check_project:
    jobs:
      - build
      - test:
          requires:
            - build
