version: 2.1

jobs:
  build_and_test: # Назва має збігатися з тим, що ви вказали в GitHub Ruleset
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Фінальна перевірка зв'язку"
          command: |
            echo "Привіт! Це CircleCI."
            echo "Якщо ти бачиш це повідомлення, значить інтеграція працює."
            echo "Зараз я просто перевіряю, що можу прочитати твій репозиторій."

workflows:
  main_workflow:
    jobs:
      - build_and_test
