apiVersion: v1
kind: ConfigMap
metadata:
  name: orders
data:
  SPRING_PROFILES_ACTIVE: mysql,rabbitmq
  SPRING_RABBITMQ_HOST: rabbitmq
  #SPRING_ACTIVEMQ_BROKERURL: tcp://activemq-0.activemq.activemq.svc:61616