apiVersion: v1
kind: Secret
metadata:
  name: orders-reader-db
data:
  url: "amRiYzptYXJpYWRiOi8vb3JkZXJzLW15c3FsOjMzMDYvb3JkZXJz"
  username: "b3JkZXJzX3VzZXI="
  password: "ZGVmYXVsdF9wYXNzd29yZA=="
---
# Source: orders/templates/mysql-writer-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: orders-writer-db
data:
  url: "amRiYzptYXJpYWRiOi8vb3JkZXJzLW15c3FsOjMzMDYvb3JkZXJz"
  username: "b3JkZXJzX3VzZXI="
  password: "ZGVmYXVsdF9wYXNzd29yZA=="