{{- if .Values.mysql.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.writer.secret.name }}
data:
  endpoint: {{ "catalog-mysql:3306" | b64enc | quote }}
  name: {{ "catalog" | b64enc | quote }}
  username: {{ "catalog_user" | b64enc | quote }}
  password: {{ "default_password" | b64enc | quote }}
{{- end }}