{{- if .Values.mysql.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.secret.name }}
data:
  username: {{ .Values.mysql.secret.username | b64enc | quote }}
  password: "{{ include "catalog.mysql.password" . }}"
{{- end }}