{{- if .Values.app.persistence.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.persistence.secret.name }}
data:
  {{- if eq "mysql" .Values.app.persistence.provider }}
  RETAIL_CATALOG_PERSISTENCE_USER: {{ .Values.app.persistence.secret.username | b64enc | quote }}
  RETAIL_CATALOG_PERSISTENCE_PASSWORD: "{{ include "catalog.persistence.password" . }}"
  {{- end }}
  {{- if .Values.app.search.enabled }}
  RETAIL_CATALOG_SEARCH_OS_USERNAME: {{ .Values.app.search.username | b64enc | quote }}
  RETAIL_CATALOG_SEARCH_OS_PASSWORD: {{ .Values.app.search.password | b64enc | quote }}
  {{- end }}
{{- end }}