{{- if .Values.app.persistence.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.persistence.secret.name }}
data:
  RETAIL_CATALOG_PERSISTENCE_USER: {{ .Values.app.persistence.secret.username | b64enc | quote }}
  RETAIL_CATALOG_PERSISTENCE_PASSWORD: "{{ include "catalog.persistence.password" . }}"
{{- end }}