name: "Setup env"
description: "Install component for devenv and nx to work"
runs:
  using: "composite"
  steps:
    - uses: cachix/install-nix-action@v26
    - uses: cachix/cachix-action@v14
      with:
        name: devenv
    - name: Install devenv.sh
      shell: bash
      run: nix profile install nixpkgs#devenv
    - name: Yarn install
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 10
        max_attempts: 3
        command: devenv shell yarn install
