{{- if .Values.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "orders.configMapName" . }}
data:
  RETAIL_ORDERS_MESSAGING_PROVIDER: rabbitmq
  SPRING_DATASOURCE_URL: {{ include "orders.postgresql.endpoint" . }}
  SPRING_RABBITMQ_ADDRESSES: {{ include "orders.rabbitmq.addresses" . }}
{{- end }}
