{{- if .Values.mysql.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mysql.writer.secret.name }}
data:
  url: {{ "jdbc:mysql://orders-mysql:3306/orders" | b64enc | quote }}
  username: {{ "orders_user" | b64enc | quote }}
  password: {{ "default_password" | b64enc | quote }}
{{- end }}