{{- if .Values.postgresql.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgresql.secret.name }}
data:
  username: {{ .Values.postgresql.secret.username | b64enc | quote }}
  password: "{{ include "orders.postgresql.password" . }}"
{{- end }}