{{- if .Values.app.messaging.rabbitmq.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.messaging.rabbitmq.secret.name }}
data:
  {{- if .Values.app.messaging.rabbitmq.secret.username }}
  SPRING_RABBITMQ_USERNAME: {{ .Values.app.messaging.rabbitmq.secret.username | b64enc | quote }}
  {{- end }}
  {{- if .Values.app.messaging.rabbitmq.secret.password }}
  SPRING_RABBITMQ_PASSWORD: {{ .Values.app.messaging.rabbitmq.secret.password | b64enc | quote }}
  {{- end }}
{{- end }}