{{- if .Values.app.persistence.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.persistence.secret.name }}
data:
  RETAIL_ORDERS_PERSISTENCE_USERNAME: {{ .Values.app.persistence.secret.username | b64enc | quote }}
  RETAIL_ORDERS_PERSISTENCE_PASSWORD: "{{ include "orders.postgresql.password" . }}"
{{- end }}