/**
 * Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
 * SPDX-License-Identifier: MIT-0
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this
 * software and associated documentation files (the "Software"), to deal in the Software
 * without restriction, including without limitation the rights to use, copy, modify,
 * merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
 * PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 * HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
 * OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

import * as http from 'http';
import { ExistingOrder } from '../model/existingOrder';
import { Order } from '../model/order';

import {
  ObjectSerializer,
  Authentication,
  VoidAuth,
  Interceptor,
  RequestOptions,
} from '../model/models';

import { HttpError } from './apis';

const defaultBasePath = 'http://localhost:8080';

// ===============================================
// This file is autogenerated - Please do not edit
// ===============================================

export enum OrdersApiApiKeys {}

export class OrdersApi {
  protected _basePath = defaultBasePath;
  protected _defaultHeaders: Record<string, string> = {};
  protected _useQuerystring = false;

  protected authentications = {
    default: <Authentication>new VoidAuth(),
  };

  protected interceptors: Interceptor[] = [];

  constructor(basePath?: string);
  constructor(
    basePathOrUsername: string,
    password?: string,
    basePath?: string,
  ) {
    if (password) {
      if (basePath) {
        this.basePath = basePath;
      }
    } else {
      if (basePathOrUsername) {
        this.basePath = basePathOrUsername;
      }
    }
  }

  set useQuerystring(value: boolean) {
    this._useQuerystring = value;
  }

  set basePath(basePath: string) {
    this._basePath = basePath;
  }

  get basePath() {
    return this._basePath;
  }

  set defaultHeaders(defaultHeaders: Record<string, string>) {
    this._defaultHeaders = defaultHeaders;
  }

  get defaultHeaders() {
    return this._defaultHeaders;
  }

  public setDefaultAuthentication(auth: Authentication) {
    this.authentications.default = auth;
  }

  public setApiKey(key: OrdersApiApiKeys, value: string) {
    (this.authentications as any)[OrdersApiApiKeys[key]].apiKey = value;
  }

  public addInterceptor(interceptor: Interceptor) {
    this.interceptors.push(interceptor);
  }

  private buildUrl(path: string, qs: RequestOptions['qs'] = {}): string {
    const url = new URL(path);

    for (const [key, value] of Object.entries(qs || {})) {
      if (value === undefined || value === null) {
        continue;
      }
      url.searchParams.append(key, String(value));
    }

    return url.toString();
  }

  private async execute<T>(
    requestOptions: RequestOptions,
    responseType: string,
  ): Promise<{ response: http.IncomingMessage; body: T }> {
    const headers = { ...(requestOptions.headers || {}) };

    if (requestOptions.auth) {
      const encoded = Buffer.from(
        `${requestOptions.auth.username}:${requestOptions.auth.password}`,
      ).toString('base64');
      headers.Authorization = `Basic ${encoded}`;
    }

    const response = await fetch(this.buildUrl(requestOptions.uri || '', requestOptions.qs), {
      method: requestOptions.method,
      headers,
      body: requestOptions.body ? JSON.stringify(requestOptions.body) : undefined,
    });

    const text = await response.text();
    const parsedBody = text ? JSON.parse(text) : undefined;
    const body = ObjectSerializer.deserialize(parsedBody, responseType);

    if (response.ok) {
      const incoming = {
        statusCode: response.status,
      } as http.IncomingMessage;

      return { response: incoming, body };
    }

    const incoming = {
      statusCode: response.status,
    } as http.IncomingMessage;
    throw new HttpError(incoming, body, response.status);
  }

  /**
   *
   * @summary Create an order
   * @param orderRequest orderRequest
   */
  public async createOrder(
    orderRequest: Order,
    options: { headers: { [name: string]: string } } = { headers: {} },
  ): Promise<{ response: http.IncomingMessage; body: ExistingOrder }> {
    const localVarPath = this.basePath + '/orders';
    const localVarHeaderParams: Record<string, string> = {
      ...this._defaultHeaders,
      ...options.headers,
      Accept: 'application/json',
      'Content-Type': 'application/json',
    };

    if (orderRequest === null || orderRequest === undefined) {
      throw new Error(
        'Required parameter orderRequest was null or undefined when calling createOrder.',
      );
    }

    const requestOptions: RequestOptions = {
      method: 'POST',
      headers: localVarHeaderParams,
      uri: localVarPath,
      qs: {},
      body: ObjectSerializer.serialize(orderRequest, 'Order'),
    };

    await this.authentications.default.applyToRequest(requestOptions);

    for (const interceptor of this.interceptors) {
      await interceptor(requestOptions);
    }

    return this.execute<ExistingOrder>(requestOptions, 'ExistingOrder');
  }

  /**
   *
   * @summary List orders
   */
  public async listOrders(
    options: { headers: { [name: string]: string } } = { headers: {} },
  ): Promise<{ response: http.IncomingMessage; body: Array<ExistingOrder> }> {
    const localVarPath = this.basePath + '/orders';
    const localVarHeaderParams: Record<string, string> = {
      ...this._defaultHeaders,
      ...options.headers,
      Accept: 'application/json',
    };

    const requestOptions: RequestOptions = {
      method: 'GET',
      headers: localVarHeaderParams,
      uri: localVarPath,
      qs: {},
    };

    await this.authentications.default.applyToRequest(requestOptions);

    for (const interceptor of this.interceptors) {
      await interceptor(requestOptions);
    }

    return this.execute<Array<ExistingOrder>>(requestOptions, 'Array<ExistingOrder>');
  }
}
