name: "Setup Docker"
description: "Sets up Docker for multi-architecture builds"
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v3
      with:
        image: tonistiigi/binfmt:latest
        platforms: all
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
outputs:
  builder:
    description: "Buildx builder name"
    value: ${{ steps.buildx.outputs.name }}
