management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: ${port:8080}

retail:
  carts:
    persistence:
      provider: "in-memory"
      dynamodb:
        endpoint:
        createTable: false
        tableName: Items
