chaos:
  monkey:
    enabled: true
    assaults:
      latencyActive: false
      level: 1
      watchedCustomServices:
        - com.amazon.sample.carts.web.CartsController.get
        - com.amazon.sample.carts.web.CartsController.delete
        - com.amazon.sample.carts.web.ItemsController.get
        - com.amazon.sample.carts.web.ItemsController.getItems
        - com.amazon.sample.carts.web.ItemsController.addToCart
        - com.amazon.sample.carts.web.ItemsController.removeItem
        - com.amazon.sample.carts.web.ItemsController.updateItem
    watcher:
      restController: true
      service: false
