openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /orders:
    get:
      tags:
        - orders
      summary: List orders
      operationId: listOrders
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExistingOrder'
    post:
      tags:
        - orders
      summary: Create an order
      operationId: createOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ExistingOrder'
components:
  schemas:
    Order:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
    OrderItem:
      type: object
      properties:
        productId:
          type: string
        quantity:
          type: integer
          format: int32
        price:
          type: integer
          format: int32
    ExistingOrder:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
        id:
          type: string
