{{- if .Values.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ui.configMapName" . }}
data:
  RETAIL_UI_THEME: {{ .Values.app.theme }}
  RETAIL_UI_CHAT_ENABLED: "{{ .Values.app.chat.enabled }}"
  RETAIL_UI_CHAT_PROVIDER: {{ .Values.app.chat.provider }}
  RETAIL_UI_CHAT_MODEL: {{ .Values.app.chat.model }}
  {{- if .Values.app.endpoints.catalog }}
  RETAIL_UI_ENDPOINTS_CATALOG: {{ .Values.app.endpoints.catalog }}
  {{- end -}}
  {{- if .Values.app.endpoints.carts }}
  RETAIL_UI_ENDPOINTS_CARTS: {{ .Values.app.endpoints.carts }}
  {{- end -}}
  {{- if .Values.app.endpoints.checkout }}
  RETAIL_UI_ENDPOINTS_CHECKOUT: {{ .Values.app.endpoints.checkout }}
  {{- end -}}
  {{- if .Values.app.endpoints.orders }}
  RETAIL_UI_ENDPOINTS_ORDERS: {{ .Values.app.endpoints.orders }}
  {{- end -}}
  {{- if .Values.app.endpoints.assets }}
  RETAIL_UI_ENDPOINTS_ASSETS: {{ .Values.app.endpoints.assets }}
  {{- end -}}
  
{{- end }}
