repositories:
- name: "stable"
  url: "https://charts.helm.sh/stable"
- name: "bitnami"
  url: "https://charts.bitnami.com/bitnami"

releases:
- name: "rabbitmq"
  namespace: "retail-sample"
  chart: bitnami/rabbitmq
  version: ~11.0.0
  wait: true

- name: "catalog"
  namespace: "retail-sample"
  chart: ../../src/catalog/chart
  wait: true
  values:
  - components.yaml.gotmpl

- name: "carts"
  namespace: "retail-sample"
  chart: ../../src/cart/chart
  wait: true
  values:
  - components.yaml.gotmpl

- name: "orders"
  namespace: "retail-sample"
  chart: ../../src/orders/chart
  wait: true
  values:
  - components.yaml.gotmpl
  - messaging:
      activemq: 
        brokerUrl: "tcp://activemq-0.activemq:61616"

- name: "checkout"
  namespace: "retail-sample"
  chart: ../../src/checkout/chart
  wait: true
  values:
  - components.yaml.gotmpl

- name: "assets"
  namespace: "retail-sample"
  chart: ../../src/assets/chart
  wait: true
  values:
  - components.yaml.gotmpl

- name: "ui"
  namespace: "retail-sample"
  chart: ../../src/ui/chart
  wait: true
  timeout: 600
  values:
    - components.yaml.gotmpl
    - ingress.yaml.gotmpl