releases:
  - name: "catalog"
    namespace: "default"
    chart: ../../catalog
    wait: true
    values:
      - templates/components.yaml.gotmpl
      - templates/catalog.yaml.gotmpl

  - name: "ui"
    namespace: "default"
    chart: ../../ui
    wait: true
    timeout: 600
    values:
      - templates/components.yaml.gotmpl
      - templates/ui.yaml.gotmpl
      - templates/ingress.yaml.gotmpl
      - retail:
          ui:
            endpoints:
              catalog: http://catalog
