name: Cart CI

on:
  push:
    branches:
      - main
    paths:
      - "src/cart/**"
  pull_request:
    branches:
      - main
    paths:
      - "src/cart/**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test-module:
    uses: ./.github/workflows/shared-ci.yml
    with:
      component: cart
    secrets: inherit
