name: UI CI

on:
  push:
    branches:
    - main
    #paths:
    #- 'src/ui/**'
  pull_request:
    branches:
    - main
    paths:
    - 'src/ui/**'

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: 17
    - name: Run
      env:
        MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"
      run: |
        src/ui/scripts/ci.sh