name: E2E Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  docker:
    name: Docker E2E Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Setup Env"
        uses: ./.github/actions/setup-env
      - name: Compose up
        run: |
          yarn nx compose:up ui
          sleep 60
      - name: Test
        run: |
          CYPRESS_BASE_URL='http://localhost:8888' yarn nx execute e2e
      - name: Compose down
        run: |
          yarn nx compose:down ui

  docker-multi:
    name: Docker E2E Tests (Multi)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Setup Env"
        uses: ./.github/actions/setup-env
      - name: Compose up
        run: |
          DB_PASSWORD='test123' yarn nx compose:up
          sleep 60
      - name: Test
        run: |
          CYPRESS_BASE_URL='http://localhost:8888' yarn nx execute e2e
      - name: Load Generator
        run: |
          cd src/load-generator
          bash scripts/run-test.sh
      - name: Compose down
        run: |
          DB_PASSWORD='test123' yarn nx compose:down
