name: "Lint PR"

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  semanticpr:
    name: "Semantic Pull Request"
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pre-commit:
    name: "Pre-commit hooks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: actions/setup-python@v5
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
      - name: Setup terraform-docs
        uses: jaxxstorm/action-install-gh-release@v1.12.0
        with:
          repo: terraform-docs/terraform-docs
      - name: Yarn install
        run: |
          yarn install
      - uses: pre-commit/action@v3.0.1
