name: Execute component CI

on:
  workflow_call:
    inputs:
      component:
        type: string
        default: "-"

permissions:
  contents: read

jobs:
  run-tests:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-docker
      - uses: ./.github/actions/setup-env
      - name: Test
        shell: devenv shell bash -- -e {0}
        run: |
          yarn nx run-many --targets=lint,test:e2e,test,build --projects=${{ inputs.component }}
      - name: Build containers
        shell: devenv shell bash -- -e {0}
        run: |
          yarn nx container ${{ inputs.component }} --platforms linux/amd64,linux/arm64 --builder ${{ steps.buildx.outputs.name }} --load false
