name: Execute component CI

on:
  workflow_call:
    inputs:
      component:
        type: string
        default: "-"

permissions:
  contents: read

jobs:
  run-tests:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Yarn install
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: devenv shell yarn install
      - name: Test
        shell: devenv shell bash -- -e {0}
        run: |
          yarn nx run-many --targets=lint,test:e2e,test,build --projects=${{ inputs.component }}
      - name: Build containers
        shell: devenv shell bash -- -e {0}
        run: |
          yarn nx container ${{ inputs.component }} --platforms linux/amd64,linux/arm64
