name: Execute component CI

on:
  workflow_call:
    inputs:
      component:
        type: string
        default: "-"

permissions:
  contents: read

jobs:
  run-tests:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv
      - name: Test
        run: nx run-many --targets=lint,test:integration,test,build --projects=${{ inputs.module }}
